-- UPDATE
-- UPDATE COMMAND IS USED FOR UPPDATE A DATA IN THE TABLE
-- SYNTAX
-- UPDATE TABLE_NAME SET COL_NAME="VALUE" WHERE COL_NAME="LOCATION " AS
SELECT * FROM students;
UPDATE students SET std_nmae = "ram" WHERE std_id = 100; 